language: go
go:
- master
install:
- go get github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: 4nUlMADnfxiLpYl7LfxUpK85dd1L4MHB3QoG2UwwEhlnEddgts8zoXIv4ohOBn+i2HuFV9jisyh+8e8ZoHyikvzkcJPJdngqsXzR07/d3jzbznoJxMb0k8DuvW4+cDmlyKqLVxO5P1pPUDTy+ZOo0Jlpb0nwfKyPD2txolnFT1BYYc3y5rW31/lhHxJQoL9GPQYSTAZ9B8Ewsk165waOALSD0xwXhet20rpIhqlzQevDUhnGX3Jxakn+NYXXzzqvWAnbTp/eBH9JJZxnfruEMS0dBG3RCE4vDMhMdSczisoIwe9/z3Mp0QGBlUCzy2FAZIGBnnIW1+r8zemYtLcu25SJMWONeHOK4gPzeLo1Nc/Nhh+AWFBdW8xTJFen0fuLI4qpE5sKHRDn2v2+iD7iCCoVEIz5qf7P3EGA9b/5sUr3zfSPkOur781zI1kNVaqJGujJKzJsLBLa8WOMyY9U+dDMDZx4aquwNyR+lfRLMXHr/liUISy9IX1ByhYDKaVWv5phrcMcDqgchpaRjhegdy8d+vG4u0UDtZ2FT11Mndnp61PVPLBya/PS2Vrgsda2uPKjPUY7l0HaysFrzHBX3ntVA7R5DiZNwuuDp7HmfesqDr1B51FoOC4ZK3o6/lTClp09x8QARsHg/8JfkFCIuQXQ0Lm+/lN2g+QT4Xa3nPc=
  - secure: RVxWnI4SDDlDRwzF4EeFbkK+Q68gbfByQvmgU8iBDULkJIPrI1hP0FYCn2XXgxcuw3Ee0zAiqe61S7owq9Ka/y9119jg+z03F/PDfgEUN4KrPbWIMjy2VCXZnjKpBOKw34kO05QcBUdCm/YlOFM/2sshiXXf41kd8OmvOMJxWmcy1YRyMXBbhxGoRxte+ud5JGSZGT0bFN15EM/f/+q+aKjfYlkav61p+SQtOkdQjO5leMiuRXJVjeJ7m4cYRWDsphukuv3kAR5PG3FGRbYGlrrU+G7wKdRK8KHuNFB/EX9EKgLs98j1/l2kxm1b5JawfCVigohL+QTAwY3ZL3EjRa6Z3JvgyaPv7YitI9c5R6CJKoSLkyz2laGqQb1dKTI9TwrPmzAsESHulxU3KddWVPTGIGIvXwSypdavI7nF1PNWRPFrkB0IqWuTTHkRIcZdr0QgEmpEM+dkF3W38zuMJl06O771Wqq/ZqCJBlLsspkyLOmw7N6o0Emp3dhAU/X8LNljRSU+gXQ1mEO8778OmHHqVlpMLCR3l/7VKz95e+Z/uIyU4VAgMQJ3SOIl14l0Bi1rqOQg1ZXpIJtupkLegH0U2/8jfc7UyVxPHD34U2cRvrS7rtpU9pPsLgFHHaHhdcYXzpLGyskAfdkF86VMOHQQFFSt4p+OLKb2u6iFmTE=
